### PR TITLE
Add a simple systemd service

### PR DESCRIPTION
**Pull request by mo-g**
So forever doesn't work desperately well, and it's bad practice anyway. Can we add this simple systemd service to the repo, so I can put it into the Pi userguide as a 'how to do this properly'?

### CODE REVIEW

**Comment by mo-g** [comment]
Having posted this, i remember the location of the udev rules in the file structure, and guess this should be moved before merging. Having shut down my workstation for the night, I'll put this right tomorrow.

Unless; would it be worth putting *both* these files in a directory of their own? `system-scripts`, `configuration-scripts` `install-scripts` `ancillary` or something?

**Comment by aelveborn** [comment]
Is this a file that needs to be copied to the correct system folder to work? So it's a template of sort?

**Comment by aelveborn** [comment]
@mo-g I'm not sure this belongs in the source code. It's more likely this belongs as an instruction in the wiki. I could see the point if this was used in an automated install sequence.

I'm not sure what to think about this. Am I just plain wrong here and this should be in the source code?
Either way, it should probably be placed in an `installation`-folder.

**Comment by mo-g** [comment]
Well, it fits the same type as the udev rules template. That's why I added it as a file for the repo. I agree with an 'installation' folder, which should contain both this and the udev rules file. Ideally, the install instructions (once finalised) should also be in the repo in an install.md or such.

There's value in having this sort of thing in the source code - the wiki doesn't get copied when forked or cloned, and having it in the source code makes things easier for creating packages from the codebase.

**Comment by mo-g** [comment]
Updated correspondingly. To be honest, I also think that the instructions belong in a `\INSTALL.md` file that gets pulled, pushed, merged, forked and version controlled, rather than in a github-specific wiki. However until the instructions are clear and working and happy, the Wiki's a good place to debug them.

**Comment by nico202** [comment]
@mo-g well, technically the wiki is a git repository (git clone https://github.com/aelveborn/Wii-Scale.wiki)

**Comment by mo-g** [comment]
I truthfully did not know that. :laughing:

**Pull request closed without merging**
